name = "playwright-mcp-example"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[browser]
binding = "BROWSER"

[[d1_databases]]
binding = "DB"
database_name = "palywright-mcp-worker"
database_id = "e1c75a9c-2ee8-4e55-87fe-5ef9791ce8cf"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlaywrightMCP"]

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "PlaywrightMCP"

[assets]
directory = "./public"        # or "./dist/client" for Vite builds
binding = "ASSETS"             # Optional: enables env.ASSETS.fetch()
not_found_handling = "single-page-application"
